version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "6672:5672"
      - "25672:15672" # The management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  iot-xray-consumer:
    build: ./iot-xray-consumer
    container_name: iot-xray-consumer-app
    environment:
      APP_PORT: 3000
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_PREFETCH_COUNT: 2
      MONGO_URI: mongodb://mongo:27017/iot-xray
    ports:
      - "4000:3000"
    depends_on:
      - mongo
      - rabbitmq

  iot-xray-producer:
    build: ./iot-xray-producer
    container_name: iot-xray-producer-app
    environment:
      APP_PORT: 3001
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_PREFETCH_COUNT: 2
    ports:
      - "4001:3001"
    depends_on:
      - rabbitmq

volumes:
  mongo_data:
